version: '3.9'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: aurelia
    ports:
      - '3306:3306'

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
      DB_NAME: aurelia
      JWT_SECRET: secret
    ports:
      - '8080:8080'
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
